[[pdoResources?
    &tpl=`eventsItemPromoIndex`
    &tplWrapper=`eventsListPromoIndex`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &includeTVs=`timeStart, viewType`
]]
[[pdoResources?
    &tpl=`topEventsSquareItemIndex`
    &tplWrapper=`topEventsSquareListIndex`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &limit=`4`
    &includeTVs=`imgSquare, timeStart, topEvent`
    &tvFilters=`topEvent==1`
]]
[[pdoResources?
    &tpl=`topEventsRectangleItemIndex`
    &tplWrapper=`topEventsRectangleListIndex`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &limit=`4`
    &includeTVs=`img, timeStart, topEvent`
    &tvFilters=`topEvent==1`
]]
[[pdoResources?
    &tpl=`videoItemIndex`
    &tplWrapper=`videoListIndex`
    &parents=`[[++themeclubcube.video_resource]]`
    &tvPrefix=``
    &includeTVs=`videoLink`
]]
[[pdoResources?
    &tpl=`blogItemIndex`
    &tplWrapper=`blogListIndex`
    &parents=`[[++themeclubcube.blog_resource]]`
    &tvPrefix=``
    &includeTVs=`img`
]]
[[pdoResources?
    &tpl=`pastEventsItemIndex`
    &tplWrapper=`pastEventsListIndex`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &limit=`2`
    &includeTVs=`timeStart, topEvent, img`
    &tvFilters=`topEvent==2`
]]
[[pdoResources?
    &tpl=`galleryItemIndex`
    &tplWrapper=`galleryListIndex`
    &parents=`[[++themeclubcube.gallery_resource]]`
    &tvPrefix=``
    &includeTVs=`img`
]]
[[pdoResources?
    &tpl=`partnersItemIndex`
    &tplWrapper=`partnersListIndex`
    &parents=`[[++themeclubcube.partners_resource]]`
    &tvPrefix=``
    &includeTVs=`img, partnerLink`
]]