[[pdoResources?
    &tpl=`eventsItemPromoIndex`
    &tplWrapper=`eventsListPromoIndex`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &includeTVs=`timeStart, viewType`
]]
[[pdoResources?
    &tpl=`topEventsSquareItemIndexEvents`
    &tplWrapper=`topEventsSquareListIndexEvents`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &limit=`6`
    &includeTVs=`imgSquare, timeStart, topEvent`
    &tvFilters=`topEvent==1`
]]
[[pdoResources?
    &tpl=`topEventsRectangleItemIndexEvents`
    &tplWrapper=`topEventsRectangleListIndexEvents`
    &parents=`[[++themeclubcube.events_resource]]`
    &tvPrefix=``
    &limit=`6`
    &includeTVs=`img, timeStart, topEvent`
    &tvFilters=`topEvent==1`
]]
[[pdoResources?
    &tpl=`videoItemIndexEvents`
    &tplWrapper=`videoListIndexEvents`
    &parents=`[[++themeclubcube.video_resource]]`
    &tvPrefix=``
    &includeTVs=`videoLink`
]]
[[pdoResources?
    &tpl=`galleryItemIndexEvents`
    &tplWrapper=`galleryListIndexEvents`
    &parents=`[[++themeclubcube.gallery_resource]]`
    &tvPrefix=``
    &includeTVs=`img`
]]